### ISSUE TITLE
[PE-D][Tester D] Marking tasks causes them to be rearranged

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-3/tp#126]
Not sure if this is the intended behaviour but marking tasks as done and undone seems to cause them to be rearranged, which is kind of confusing

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: reneeyeow02/ped#2

**Comment by neosunhan** [comment]
Intended behaviour, maybe we can document this clearly in the User Guide to make this less confusing.
