### ISSUE TITLE
[PE-D][Tester C] Able to take decimals as input for marks even though only integers were meant to be taken

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-3/tp#127]
![Screenshot 2022-10-28 at 4.30.55 PM.png](https://raw.githubusercontent.com/amresh2000/ped/main/files/35272474-c0a7-43d2-beec-d587ca787b1b.png)

![Screenshot 2022-10-28 at 4.31.47 PM.png](https://raw.githubusercontent.com/amresh2000/ped/main/files/d5ab8433-cb2c-439d-947c-62c67851dd9e.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: amresh2000/ped#2

**Comment by neosunhan** [comment]
Marks input can take on non-integer values, tester misread User Guide.
