### ISSUE TITLE
[PE-D][Tester C] At certain sizes exterior scroll bar disappears. User might not know how to scroll

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-3/tp#135]
![Screenshot 2022-10-28 at 4.53.57 PM.png](https://raw.githubusercontent.com/amresh2000/ped/main/files/fd6b6407-8b38-491f-a75e-63131ff4e9ea.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: amresh2000/ped#4

**Comment by neosunhan** [comment]
Not a bug
