### ISSUE TITLE
[PE-D][Tester E] Users are allowed to add deadlines that are in the past.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T11-3/tp#136]
`addtask t/Test d/2000-01-10` is allowed even though it is 22 years ago.

![image.png](https://raw.githubusercontent.com/seox123/ped/main/files/7b86ab44-10c9-4b2f-b237-ea390573a217.png)

Users may have entered the year wrongly. Maybe you could conduct a check to see if the deadline given is before today's date, and throw an error if it is.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: seox123/ped#5

**Comment by neosunhan** [comment]
Intended functionality
